language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t deepakraog/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true deepakraog/multi-docker npm test

after_success:
  - docker build -t deepakraog/multi-client ./client
  - docker build -t deepakraog/multi-nginx ./nginx
  - docker build -t deepakraog/multi-server ./server
  - docker build -t deepakraog/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push deepakraog/multi-client
  - docker push deepakraog/multi-nginx
  - docker push deepakraog/multi-server
  - docker push deepakraog/multi-worker

  deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-695924387382'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY